/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as homeAboutRouteImport } from './routes/(home)/about'
import { Route as homeVmiIndexRouteImport } from './routes/(home)/vmi/index'
import { Route as homeBacktestIndexRouteImport } from './routes/(home)/backtest/index'

const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const homeAboutRoute = homeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeVmiIndexRoute = homeVmiIndexRouteImport.update({
  id: '/vmi/',
  path: '/vmi/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeBacktestIndexRoute = homeBacktestIndexRouteImport.update({
  id: '/backtest/',
  path: '/backtest/',
  getParentRoute: () => homeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof homeAboutRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof homeIndexRoute
  '/backtest/': typeof homeBacktestIndexRoute
  '/vmi/': typeof homeVmiIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof homeAboutRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof homeIndexRoute
  '/backtest': typeof homeBacktestIndexRoute
  '/vmi': typeof homeVmiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(home)/about': typeof homeAboutRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/(home)/': typeof homeIndexRoute
  '/(home)/backtest/': typeof homeBacktestIndexRoute
  '/(home)/vmi/': typeof homeVmiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/demo/tanstack-query' | '/' | '/backtest/' | '/vmi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/demo/tanstack-query' | '/' | '/backtest' | '/vmi'
  id:
    | '__root__'
    | '/(home)'
    | '/(home)/about'
    | '/demo/tanstack-query'
    | '/(home)/'
    | '/(home)/backtest/'
    | '/(home)/vmi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/about': {
      id: '/(home)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/vmi/': {
      id: '/(home)/vmi/'
      path: '/vmi'
      fullPath: '/vmi/'
      preLoaderRoute: typeof homeVmiIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/backtest/': {
      id: '/(home)/backtest/'
      path: '/backtest'
      fullPath: '/backtest/'
      preLoaderRoute: typeof homeBacktestIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeAboutRoute: typeof homeAboutRoute
  homeIndexRoute: typeof homeIndexRoute
  homeBacktestIndexRoute: typeof homeBacktestIndexRoute
  homeVmiIndexRoute: typeof homeVmiIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeAboutRoute: homeAboutRoute,
  homeIndexRoute: homeIndexRoute,
  homeBacktestIndexRoute: homeBacktestIndexRoute,
  homeVmiIndexRoute: homeVmiIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
